# Generated by Django 5.0.8 on 2025-01-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('normal', 'Normal User'), ('farmer', 'Farmer'), ('admin', 'Admin')], default='normal', max_length=20),
        ),
    ]
