# Generated by Django 5.0.8 on 2025-02-01 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_role_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_location', models.CharField(max_length=255)),
                ('occupation_name', models.CharField(max_length=255)),
                ('user_role', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Farmer_Profile', to='myapp.userrole')),
            ],
        ),
    ]
