# Generated by Django 5.0.8 on 2025-02-01 10:28

import django.core.validators
import django.db.models.deletion
import myapp.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_farmerprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/images', validators=[myapp.models.validate_file_size, django.core.validators.FileExtensionValidator(['jpg', 'png'])])),
                ('availability_status', models.BooleanField(default=True)),
                ('quantity', models.IntegerField()),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user_manual', models.FileField(blank=True, null=True, upload_to='uploads/manuals', validators=[myapp.models.validate_file_size, django.core.validators.FileExtensionValidator(['pdf', 'docx'])])),
                ('delivery_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
