# Generated by Django 5.0.8 on 2025-02-07 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_hourly_rate_equipment_per_day_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='availability_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='quantity',
            field=models.IntegerField(default=5),
        ),
        migrations.DeleteModel(
            name='EquipmentStock',
        ),
    ]
