# Generated by Django 5.0.8 on 2025-02-10 10:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_equipmentpayment_delete_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentpayment',
            name='payment_type',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='offline', max_length=50),
        ),
        migrations.CreateModel(
            name='EquipmentDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('delivering', 'Delivering'), ('delivered', 'Delivered')], default='processing', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipment_payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='myapp.equipmentpayment')),
            ],
        ),
    ]
