# Generated by Django 5.0.8 on 2025-02-10 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_equipmentpayment_payment_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentpayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
