# Generated by Django 5.0.8 on 2025-02-12 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_category_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='meta_keywords',
        ),
        migrations.RemoveField(
            model_name='category',
            name='meta_title',
        ),
    ]
