# Generated by Django 5.0.8 on 2025-02-17 08:01

import datetime
import django.core.validators
import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_rename_trades_trade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirmedtrade',
            name='confirmed_by',
        ),
        migrations.RemoveField(
            model_name='traderequest',
            name='requested_product',
        ),
        migrations.AddField(
            model_name='confirmedtrade',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('delivering', 'Delivering'), ('delivered', 'Delivered'), ('canceled', 'Canceled')], default='processing', max_length=50),
        ),
        migrations.AddField(
            model_name='confirmedtrade',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='trade_ending_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 17, 8, 1, 40, 804071, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='trade',
            name='wanted_price',
            field=models.IntegerField(default=22),
        ),
        migrations.AddField(
            model_name='trade',
            name='wanted_product',
            field=models.CharField(default='abc', max_length=255),
        ),
        migrations.AddField(
            model_name='trade',
            name='wanted_quantity',
            field=models.IntegerField(default=22),
        ),
        migrations.AddField(
            model_name='traderequest',
            name='delivery_location',
            field=models.CharField(default='abc', max_length=255),
        ),
        migrations.AddField(
            model_name='traderequest',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/trade-request-img', validators=[myapp.models.validate_file_size, django.core.validators.FileExtensionValidator(['jpg', 'png'])]),
        ),
        migrations.AddField(
            model_name='traderequest',
            name='note',
            field=models.TextField(default='abc', max_length=255),
        ),
        migrations.AddField(
            model_name='traderequest',
            name='price',
            field=models.DecimalField(decimal_places=2, default=22, max_digits=10),
        ),
        migrations.AddField(
            model_name='traderequest',
            name='product_name',
            field=models.CharField(default='abc', max_length=255),
        ),
        migrations.AddField(
            model_name='traderequest',
            name='quantity',
            field=models.PositiveIntegerField(default=22),
        ),
        migrations.AddField(
            model_name='traderequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=255),
        ),
    ]
