# Generated by Django 5.0.8 on 2025-02-17 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_remove_confirmedtrade_confirmed_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='trade_ending_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='trade',
            name='wanted_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='trade',
            name='wanted_product',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='trade',
            name='wanted_quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='traderequest',
            name='delivery_location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='traderequest',
            name='note',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='traderequest',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='traderequest',
            name='product_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='traderequest',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
