# Generated by Django 5.0.8 on 2025-02-22 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_alter_trade_trade_ending_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmedtrade',
            name='item_location',
            field=models.CharField(blank=True, default='asas', max_length=255, null=True),
        ),
    ]
