# Generated by Django 5.0.8 on 2025-02-22 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_confirmedtrade_item_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmedtrade',
            name='item_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
