# Generated by Django 5.0.8 on 2025-02-22 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_alter_confirmedtrade_item_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmedtrade',
            name='item_location',
            field=models.CharField(default='Not available', max_length=255),
        ),
    ]
