# Generated by Django 5.0.8 on 2025-02-22 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_alter_confirmedtrade_item_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmedtrade',
            name='item_received',
            field=models.BooleanField(default=False),
        ),
    ]
