# Generated by Django 5.0.8 on 2025-02-27 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_confirmedtrade_item_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentdelivery',
            name='equipment_received',
            field=models.BooleanField(default=False),
        ),
    ]
