# Generated by Django 5.0.8 on 2025-03-02 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_alter_product_delivery_sell_charge_cartpayment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartpayment',
            name='delivery_address',
            field=models.CharField(max_length=255),
        ),
    ]
