# Generated by Django 5.0.8 on 2025-03-02 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_alter_cartpayment_delivery_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartpayment',
            name='cart',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart_payment', to='myapp.cart'),
        ),
    ]
