# Generated by Django 5.0.8 on 2025-03-02 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_alter_cartdelivery_cart_payment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartdelivery',
            name='user',
        ),
        migrations.AlterField(
            model_name='cartdelivery',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cartdelivery',
            name='delivery_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
