# Generated by Django 5.0.8 on 2025-03-02 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_remove_cartdelivery_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartpayment',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
