# Generated by Django 5.0.8 on 2025-03-02 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_remove_cartpayment_total_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartdelivery',
            name='item_location',
        ),
        migrations.AddField(
            model_name='cartdelivery',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_deliveries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cartdelivery',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('owner_to_admin', 'Owner to Admin'), ('admin_received', 'Admin Received'), ('delivering_to_user', 'Delivering to User'), ('delivered', 'Delivered'), ('canceled', 'Canceled')], default='pending', max_length=50),
        ),
        migrations.CreateModel(
            name='CartProductDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('owner_to_admin', 'Owner to Admin'), ('delivered_to_admin', 'Delivered to Admin')], default='pending', max_length=50)),
                ('handover_date', models.DateTimeField(blank=True, null=True)),
                ('cart_delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_product_deliveries', to='myapp.cartdelivery')),
                ('product_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_deliveries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
