# Generated by Django 5.0.8 on 2025-03-09 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0038_cartdelivery_delivery_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartdelivery',
            name='handover_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cartdelivery',
            name='status',
            field=models.CharField(choices=[('delivered_to_admin', 'Delivered to Admin'), ('delivering_to_admin', 'Delivering to Admin'), ('pending', 'Pending'), ('owner_to_admin', 'Owner to Admin'), ('admin_received', 'Admin Received'), ('delivering_to_user', 'Delivering to User'), ('delivered', 'Delivered'), ('canceled', 'Canceled')], default='pending', max_length=50),
        ),
        migrations.DeleteModel(
            name='CartProductDelivery',
        ),
    ]
