# Generated by Django 5.0.8 on 2025-03-20 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0040_alter_cartdelivery_cart_payment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='wanted_price',
        ),
        migrations.AddField(
            model_name='trade',
            name='trading_quantity',
            field=models.PositiveIntegerField(default=20),
        ),
    ]
