# Generated by Django 5.0.8 on 2025-03-20 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0041_remove_trade_wanted_price_trade_trading_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='trading_quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
