# Generated by Django 5.0.8 on 2025-03-21 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0042_alter_trade_trading_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traderequest',
            name='price',
        ),
    ]
