# Generated by Django 5.0.8 on 2025-03-21 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0043_remove_traderequest_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traderequest',
            name='quantity',
        ),
    ]
