# Generated by Django 5.0.8 on 2025-05-15 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0044_remove_traderequest_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentdelivery',
            name='equipment_received_by_owner',
            field=models.BooleanField(default=False),
        ),
    ]
