# Generated by Django 5.0.8 on 2025-05-16 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0045_equipmentdelivery_equipment_received_by_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmedtrade',
            name='item_received_by_owner',
            field=models.BooleanField(default=False),
        ),
    ]
