import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { AuthProvider } from "../utils/auth";
import { EquipProvider } from "../utils/equip";
import { ProductProvider } from "../utils/prod";

import "./globals.css";
import Navbar from "./components/Navbar/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
        <EquipProvider>
            <ProductProvider>
              <Navbar />
                  <main className="flex-grow">
                    {children}
                  </main>
                </ProductProvider>
              </EquipProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
